# Generated by Django 3.2 on 2023-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(unique=True, verbose_name='Имя пользователя'),
        ),
    ]
